liongram/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from posts.views import index, url_view, url_parameter_view,function_list_view,function_view, class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/',url_view),
    path('url/<str:username>/',url_parameter_view),
    path('fbv/list',function_list_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    path('', index, name='index'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('__debug__/', include('debug_toolbar.urls')),
    
]    

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path

from .views import post_list_view, post_create_view,post_create_form_view,post_update_view,post_detail_view,post_delete_view

app_name ='posts'

urlpatterns = [
    path('',post_list_view, name='post-list'),
   # path('create/',post_create_view, name='post-create'),
    path('create/',post_create_form_view, name='post-create'),
    path('<int:id>/',post_detail_view, name='post-detail'),
    path('<int:id>/edit/',post_update_view, name ='post-update'),   
    path('<int:id>/delete/',post_delete_view, name='post-delete'),
]

liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
# Create your models here.

class Post(models.Model):
    image = models.ImageField(verbose_name='이미지',null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일',auto_now_add= True)
    view_count = models.IntegerField(verbose_name='조회수',default = 0 )
    writer = models.ForeignKey(to=User, on_delete = models.CASCADE, null=True, blank=True)

class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일',auto_now_add=True)
    post = models.ForeignKey(to='Post',on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User,on_delete=models.CASCADE,null=True,blank=True)

liongram/posts/forms.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from .models import Post
#class PostBaseForm(forms.Form):
#    CATEGORY_CHOICES =[
#        ('1','일반'),
#        ('2','계정'),
#    ]
#    image = forms.ImageField(label='이미지')
#    content = forms.CharField(label='내용',widget=forms.Textarea, required=True)
#    category = forms.ChoiceField(label='카테고리',choices=CATEGORY_CHOICES)

class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =  '__all__'

class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields=['image','content']

    def clean_content(self) -> Optional[Dict[str,Any]]:
        data = self.cleaned_data["content"]
        if "비속어" == data:
            raise forms.ValidationError("비속어는 사용 불가!")

        return data
    
class PostUpdateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields=['image','content']

class PostDetailForm(PostBaseForm):
    def __init__(self, *args, **kwargs):
        super(PostDetailForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields['content'].widget.attrs['disabled'] = True

liongram/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404, HttpResponse, JsonResponse

from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostBaseForm , PostCreateForm , PostDetailForm

def index(request):
    post_list = Post.objects.all().order_by('-created_at') #Post 전체 데이터 조회

    context = {
        'post_list':post_list,

    }
    return render(request,'index.html',context)

def post_list_view(request):
    post_list = Post.objects.all() #Post 전체 데이터 조회
   # post_list = Post.objects.filter(writer=request.user) #post.writer가 현재 로그인인 것 조회 
   # post_list = None 
    context = {
        'post_list':post_list,

    }
    return render(request,'posts/post_list.html',context)

def post_detail_view(request, id):

    try:
        post = Post.objects.get(id=id)
    except Post.DoesNotExist:
        return redirect('index')
    context = {
        'post':post,
        'form':PostDetailForm(),
    }

    return render(request,'posts/post_detail.html', context)

@login_required
def post_create_view(request):
    if request.method =='GET':
        return render(request,'posts/post_form.html')
    else:
        image= request.FILES.get('image')
        content= request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create(
            image= image,
            content=content,
            writer=request.user
        )
        return redirect('index')

def post_create_form_view(request):
    if request.method =='GET':
        form = PostCreateForm()
        context = {'form':form}
        return render(request,'posts/post_form2.html', context)
    else:
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
         Post.objects.create(
            image= form.cleaned_data['image'],
            content= form.cleaned_data['content'],
            writer=request.user
            )
        else:
            return redirect('posts:post-create')
        return redirect('index')
    
def post_update_view(request, id):
    post = get_object_or_404 (Post, id=id)
    if request.method == 'GET':
        context = { 'post':post }
        return render(request,'posts/post_form.html', context)
    elif request.method == 'POST':
        new_image= request.FILES.get('image')
        content= request.POST.get('content')
        print(new_image)
        print(content)
        if new_image:
            post.image.delete()
            post.image = new_image
    
        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)

#@login_required
def post_delete_view(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.writer:
        raise Http404('잘못된 접근입니다')
    if request.method == 'GET':
        context= { 'post' : post}
        return render(request, 'posts/post_confirm_delete.html', context)
    else:
        post.delete()
        return redirect('index')



#fbv
def url_view(request):
    print('url_view()')
    data ={'code': '001', 'msg':'OK'}
    return HttpResponse('<h1>url_view</h1>')
    #return JsonResponse(data)


    #데이터 받는 방법 
def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username:{username}')
    print(f'request.GET:{request.GET}')
    return HttpResponse(username)


def function_view(request):
    
    print(f'request.method:{request.method}')
    if request.method =='GET':
        print(f'request:GET:{request.GET}')
    elif request.method =='POST':
        print(f'request:POST:{request.POST}')
#    return render(request,'view.html')

class class_view(ListView):
    model = Post
    ordering= ['-id']
    #template_name = 'cbv_view.html'
   

def function_list_view(request):
    object_list = Post.objects.all().order_by('-id')
    return render(request,'cbv_view.html',{'object_list':object_list})

liongram/templates/posts/post_confirm_delete.html
{%extends 'base.html' %}
{% block title %}글 삭제{% endblock %}

{% block content %}
    <h1>Post 삭제 화면</h1>
    <form action ="" method ="POST">
        {% csrf_token %}
        <p>한번 삭제된 데이터는 복구가 불가능합니다. </p>
        <p>그래도 삭제하시겠습니까? ID: {{post.id}}</p><br/><br/>
        <a href ="{% url 'index' %}">돌아가기</a>
        <input type = "submit" value="삭제하기">
    </form>
    <hr>
    {% include 'mixin/posts/post_card.html' with detail=True %}
    {% endblock%} 

liongram/templates/posts/post_detail.html
{%extends 'base.html' %}
{% block title %}글 상세{% endblock %}

{% block content %}
    <h1>Post 상세 화면</h1>
    {% include 'mixin/posts/post_card.html'  with detail=True %}

        {{ form.as_p}}
    {% endblock%}

liongram/templates/posts/post_form.html
{%extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
    <h1>Post 입력 화면</h1>

    <form action="" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div>
            <label for="id_image">이미지</label>
            {% if post.image %}
            <p>현재 : <a href="{{ post.image.url }}"> {{ post.image.name }}</a></p>
            <p>변경 : <input type="file" name ="image" accept="image/*" id="id_image"></p>
            {% else %}
            <input type="file" name ="image" accept="image/*" id="id_image">
            {% endif %}
        </div>
        <div>
            <label for="id_content">내용</label>
            <textarea name="content" id="id_content" cols="30" rows="10">
                {% if post %}
                {{ post.content }}
            {% endif %} 
            </textarea>
          
        </div>
        <div>
            <input type="submit">
        </div>
    </form>
    {% endblock%}

liongram/templates/posts/post_form2.html
{%extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
    <h1>Post 입력 화면- form 사용</h1>

    <form action="" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}
        <div>
            {{ form.as_p }}
          <!-- {% for field in form %}
             {{ field }}
             {% endfor %}-->  
        </div>
        <div>
            <input type="submit">
        </div>
    </form>
    {% endblock%}

liongram/templates/posts/post_list.html
{%extends 'base.html' %}
{% block title %}글 목록{% endblock %}

{% block content %}
    <h1>Post 목록 화면</h1>
    <!--   {{ post_list }} -->

    {% for post in post_list %}
        <div>
        {{ post.id }}<br/>
        {{ post.image }}<br/>
        {{ post.content }}<br/>
        {{ post.created_at }}<br/>
        {{ post.writer }}<br/>
        </div>
    {%endfor%}
    {% endblock%}