liongram/accounts/urls.py
from django.urls import path 

from .views import signup_view ,login_view,logout_view

app_name ='accounts'

urlpatterns = [

    path('signup/',signup_view, name='signup'),
    path('login/',login_view, name='login'),
    path('logout/',logout_view, name='logout'),
]

liongram/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from posts.views import index, url_view, url_parameter_view,function_list_view,function_view, class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/',url_view),
    path('url/<str:username>/',url_parameter_view),
    path('fbv/list',function_list_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    path('', index, name='index'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('posts/',include('posts.urls',namespace='posts')),
    path('__debug__/', include('debug_toolbar.urls')),
    
]    

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path

from .views import post_list_view, post_create_view,post_create_form_view,post_update_view,post_detail_view,post_delete_view

app_name ='posts'

urlpatterns = [
    path('',post_list_view, name='post-list'),
   # path('create/',post_create_view, name='post-create'),
    path('create/',post_create_form_view, name='post-create'),
    path('<int:id>/',post_detail_view, name='post-detail'),
    path('<int:id>/edit/',post_update_view, name ='post-update'),   
    path('<int:id>/delete/',post_delete_view, name='post-delete'),
]

liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{%static 'css/reset.css' %}">
    <link rel="stylesheet" href="{%static 'css/index.css' %}">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>
<body class="container">
    <div>
        {% block content %}
        {% endblock%}
    </div>
   

    <div>
        <nav>
           <ul class="bottom-menu-group">
            <li>
                <a href="{% url 'index' %}">
                <img src ="{% static 'icons\home_outlined_black_36dp.svg' %}" alt='홈'>
                </a>
            </li>
            
            
                <li><img src ="{% static 'icons\search_outlined_black_36dp.svg' %}" alt='검색'></li>
            <li>
                <a href="{% url 'posts:post-create' %}">
                <img src ="{% static 'icons\add_box_outlined_black_36dp.svg' %}" alt='글쓰기'></li>
                </a>
                <li><img src ="{% static 'icons\favorite_outlined_black_36dp.svg' %}" alt='좋아요'></li>
            <li><img src ="{% static 'icons\account_circle_outlined_black_36dp.svg' %}" alt='프로필'></li>
           </ul> 
        </nav>
    </div>
    {% if request.user.is_authenticated %}
    <span>
        로그인상태: {{ request.user.username}}
        <a href="{% url 'accounts:logout'%}">로그아웃</a>
    </span>
    {% else %}
    <span>(비로그인상태)
        <a href="{% url 'accounts:login'%}">로그인</a>
        <a href="{% url 'accounts:signup'%}">회원가입</a>
    </span>
    {% endif %}


</body>
</html>

liongram/templates/index.html
{%extends 'base.html' %}
{% load static %}

{% block title %}인덱스{% endblock %}

{% block content %}
  <main>
    <div class = "card-list">
      {% for post in post_list %}
        {% include 'mixin/posts/post_card.html' with detail=False %}
      {% endfor %}
      </div>
   
  </main>
 
{% endblock%}